version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - dash

  dash:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"

networks:
  default:
    external:
      name: cmoos_network
